services:
  db:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d weatherdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    depends_on:
        db:
            condition: service_healthy
    restart: on-failure

volumes:
  db_data:
